export const listProject = [
  {
    name: "Web Ecommerce",
    pathImage: "/projects/Ecommerce.png",
    linkDemo: "https://the-wild-oasis-phi-weld-42.vercel.app/",
    techList: [
      "ReactJS",
      "NodeJS",
      "Express",
      "MongoDB",
      "Socket.io",
      "Tailwindcss",
    ],
    descriptionVi: "Dự án Web Thương mại điện tử",
    descriptionEn: "This is Web Ecommerce",
  },
  {
    name: "Facbook clone",
    pathImage: "/projects/facebook.png",
    linkDemo: "https://the-wild-oasis-phi-weld-42.vercel.app/",
    techList: ["ReactJS", "NodeJS", "Express", "MongoDB", "Tailwindcss"],
    descriptionVi: "Dự án Facebook",
    descriptionEn: "This is Facebook",
  },
  {
    name: "Trello Clone",
    pathImage: "/projects/trello.png",
    linkDemo: "https://trello-web-tau-nine.vercel.app/",
    techList: [
      "ReactJS",
      "NodeJS",
      "Express",
      "MongoDB",
      "Tailwindcss",
      "Material Ui",
    ],
    descriptionVi: "Dự án clone MERN STACK trello",
    descriptionEn: "MERN STACK trello clone project",
  },
  {
    name: "The wild oasis mini",
    pathImage: "/projects/wildoasis.png",
    linkDemo: "https://the-wild-oasis-phi-weld-42.vercel.app/",
    techList: ["NextJS", "Database Supabase", "Tailwindcss"],
    descriptionVi: "Dự án web du lịch",
    descriptionEn: "This is booking travel",
  },
];
